<?php


namespace Controller;


use Core\Config;
use Model\DiaryModel;
use Model\UsersModel;
use TexLab\MyDB\DB;
use TexLab\MyDB\DbEntity;
use View\View;

class DiaryIdController extends DiaryController

{

    public function actionShow(array $data)
    {
        parent::actionShow($data); // TODO: Change the autogenerated stub

//        print_r($_SESSION);
        $this->view
            ->setFolder("diaryId")
            ->addData(
                [
                    "user_id" => $_SESSION['user']['id'],
                    "usersList" => $this->usersTable->getUsers(),
                    'table' => $this
                        ->table
                        ->reset()
                        ->setPageSize(Config::PAGE_SIZE_DIARY)
                        ->diaryUserFilter($data['get']['page'] ?? 1, $_SESSION['user']['id']),
                    'fields' => array_diff($this->table->getColumnsNames(), ['id']),
                    'comments' => $this->table->getColumnsComments(),
                    'type' => $this->getClassName(),
                    'pageCount' => $this->table->pageCountDiary($_SESSION['user']['id'])
                ]
            );
    }

    public function actionShowEdit(array $data)
    {
        parent::actionShowEdit($data); // TODO: Change the autogenerated stub

        $this
            ->view
            ->setFolder('diaryId');

        $this->view->addData(
            [
                "usersList" => $this->usersTable->getUsers(),
            ]
        );
    }

    public function actionAddExercise(array $data)
    {
        $users_id = $_SESSION['user']['id'];
        /** @var string $exerxise */
        $exerxise = $data['get']['exercise'];

        $this->table->getAddExercise($users_id, $exerxise);
        $this->redirect('?action=show&type=DiaryId');
    }

    public function actionPlanA()
    {
        $users_id = $_SESSION['user']['id'];

        $this->table->randPlan1($users_id);
        $this->redirect('?action=show&type=DiaryId');
    }
    public function actionPlanB()
    {
        $users_id = $_SESSION['user']['id'];

        $this->table->randPlan2($users_id);
        $this->redirect('?action=show&type=DiaryId');
    }
    public function actionPlanC()
    {
        $users_id = $_SESSION['user']['id'];

        $this->table->randPlan3($users_id);
        $this->redirect('?action=show&type=DiaryId');
    }
}