<?php

namespace Controller;

use Core\Config;

class SignUpController extends UsersController
{
    public function actionShow(array $data)
    {
        if (!empty($data)) {
            $this
                ->view
                ->setFolder('signup')
                ->setTemplate('show')
                ->setLayout('planeLayout')
                ->addData([]);
        }else{
            echo 321;
        }
    }


    public function actionShowEdit(array $data)
    {
    }

    public function actionAdd(array $data)
    {

        $data['post']['group_id'] = $this->table->getGroupIdByCode('user');
        if (!empty($data)) {
            parent::actionAdd($data); // TODO: Change the autogenerated stub
            $this->redirect('?action=loginform&type=auth');
        }else{
            echo 123;
        }

    }

    public function actionEdit(array $data)
    {
    }

    public function actionDel(array $data)
    {
    }
}
